"""Add password column to users

Revision ID: 9ccdf03cdb60
Revises: 0c466b5d83e5
Create Date: 2025-02-23 19:20:37.536849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ccdf03cdb60'
down_revision = '0c466b5d83e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('github_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('github_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###
