"""empty message

Revision ID: a20a3f4e8ab1
Revises: e1e28cd6858a
Create Date: 2025-02-18 12:37:32.211730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a20a3f4e8ab1'
down_revision = 'e1e28cd6858a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
